---
abstract: 'Test module that sums'
author:
  - 'André Philipp <aphilipp@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.112150'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-APHILIPP-Utils
provides:
  Acme::APHILIPP::Utils:
    file: lib/Acme/APHILIPP/Utils.pm
    version: 0.03
  Tie::Cycle:
    file: lib/Tie/Cycle.pm
    version: 0.01
resources:
  license: http://opensource.org/licenses/artistic-license-2.0.php
version: 0.03
